### PR TITLE
IA-2397 Add terra-app-setup-chart

### PR DESCRIPTION
**Pull request by Qi77Qi**
Tested in fiab with https://github.com/DataBiosphere/leonardo/pull/1866

* Add a terra-app-setup-chart outlined in [here](https://broadworkbench.atlassian.net/wiki/spaces/IA/pages/1355907081/2020-02-08+Use+leonardo-set-up+chart). This chart will create service account and certs as secrets required for deploying galaxy and custom apps.

Will test things out in a fresh new fiab since I did something manually on current fiab

### CODE REVIEW

**Comment by jdcanas** [comment]
Is adding the empty .crt and .key files intentional? If so, what is the use case, some sort of testing stub?

**Comment by Qi77Qi** [comment]
@jdcanas yea, it's just allowing the chart to be deployed locally on minikube....

**Review by rtitle — APPROVED** [review]
LGTM, so long as it's tested through Leo.

Question: does this chart need to be added to the `terra-app-local.sh` script for deploying to minikube? I'm guessing not because it just handles KSAs and TLS secrets, neither of which are needed for local minikube deployment. If this chart starts handling stuff like ingress though we would need to bake it into the script.

**Comment by Qi77Qi** [comment]
yea...the chart is tested in leo and things work as expected...

I didn't really try it out on minikube becuz I wasn't able to start minikube. It just hangs for ever to start. But I think `terra-app-local.sh` should work as before becuz set up chart is a separate chart. It's just the script won't deploy the setup chart.

**Pull request merged**
