### PR TITLE
[no ticket][risk=no] Add GOMEMLIMIT=20MiB env var to make BQ connector working

### PR DESCRIPTION
**Pull request by yonghaoy**
Verified and it works for me after adding this env var

### CODE REVIEW

**Review by Qi77Qi — COMMENTED** [review]
we should make this an argument that gets passed in by Leonardo

**Comment by Qi77Qi** [comment]
haven't been able to verify this working for myself e2e yet...but think this definitely fixes the GO error..

One comment tho

**Comment by yonghaoy** [comment]
> we should make this an argument that gets passed in by Leonardo

Or, I can make this as an `extraVar` passed by AoU. 
https://github.com/DataBiosphere/leonardo/blob/29213d446aac528c9ab8a5feec4e157a1f7ddfe1/http/src/main/resources/swagger/api-docs.yaml#L4014?

**Comment by Qi77Qi** [comment]
@yonghaoy sure yea, either way works..I think that'll be better than updating the chart

**Comment by Qi77Qi** [comment]
actually, I think we should make this change in leo cuz Terra will have the same issue...

I'll upadte this PR once we've verified things are working

**Comment by Qi77Qi** [comment]
hmm...maybe let's have this for now..if we have a reason to update this in the future, we can parameterize this

**Pull request merged**
